build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file --coverage-text test.php
                coverage:
                    file: my-coverage-file
                    format: php-clover
    environment:
        php:
            version: 5.5.12
filter:
    paths: [uri.class.php]
checks:
    php:
        verify_property_names: true
        code_rating: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        uppercase_constants: true
        uppercase_basic_constants: true
        verify_access_scope_valid: true
        return_doc_comments: true
        require_php_tag_first: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_braces_around_control_structures: true
        remove_trailing_whitespace: true
        remove_php_closing_tag: true
tools:
    external_code_coverage: true
